version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=file:../src/database/stockDB.db
    command: npm run dev
